spring.application.name=ticket-tracking-system

spring.datasource.url=jdbc:postgresql://localhost:5433/ticket_tracking
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

