spring.application.name=ticket-tracking-system

spring.datasource.url=jdbc:postgresql://localhost:5433/ticket_tracking
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver


resend.apiKey=${RESEND_API_KEY}
resend.baseUrl=https://api.resend.com
resend.from=Ticket Tracking <onboarding@resend.dev>

b2.endpoint=https://s3.us-west-004.backblazeb2.com
b2.region=us-west-004
b2.access-key=${B2_ACCESS_KEY}
b2.secret-key=${B2_SECRET_KEY}
b2.bucket=${B2_BUCKET}
b2.presigned-url-expiration-minutes=20

security.jwt.secret=${JWT_SECRET}

logging.level.org.springframework.security=DEBUG